# Generated by Django 3.0.5 on 2020-05-01 10:21

from django.db import migrations, models

import api.helpers.image_helper


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20200430_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, max_length=254, null=True,
                                            upload_to=api.helpers.image_helper.nameFile)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
