# Generated by Django 3.0.5 on 2020-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
