# Generated by Django 3.0.5 on 2020-05-02 17:57

from django.db import migrations, models

import api.helpers.image_helper


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_uploadimage_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='thumbnail_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=api.helpers.image_helper.nameFile),
        ),
    ]
